\input texinfo
@c $Id$
@setfilename gtksurf.info
@settitle gtksurf
@setcontentsaftertitlepage

@include version.texi

@ifinfo
This file documents @emph{gtksurf} -- the graphical frontend to @emph{surf}.

Copyright (C) 2001 Johannes Beigel
@end ifinfo

@c title page
@c **********

@titlepage
@title gtksurf
@subtitle a graphical frontend to @emph{surf}
@author Johannes Beigel

@c copyright page
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2001 Johannes Beigel
@end titlepage


@c Top node
@c ********

@ifinfo

@node Top, Copying, , (dir)
@top surf

This document describes the usage of @emph{gtksurf}, the graphical
frontend to @emph{surf}.

This document applies to version @value{VERSION} of @emph{gtksurf}.
Although it may hopefully be well readable in info format with any info
reader (preferably XEmacs) or in HTML format, it will look best as DVI
file produced by @command{texi2dvi}: Just do a @kbd{make dvi} in the
@file{docs/} directory of the @emph{gtksurf} distribution.

@menu
* Copying::
* Overview::
@end menu

@end ifinfo

@c Copying
@c *******

@node Copying, Overview, top, top
@unnumbered Copying

Copyright @copyright{} 2001 Johannes Beigel

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

@c Overview
@c ********

@node Overview, , Copying, top
@chapter Overview

@bye
