dummy:
	    @echo ' '
	    @echo 'usage:'
	    @echo ' '
	    @echo '    run the demo:'
	    @echo '        make all'
	    @echo ' '
	    @echo '    clean up:'
	    @echo '        make clean'
	    @echo ' '

all:
	surf cyclide.pic
	surf multicurve.pic
	latex demo


clean:
	/bin/rm demo.aux
	/bin/rm demo.log
	/bin/rm demo.dvi
	/bin/rm mc.tex
	/bin/rm cyc.tex
	/bin/rm *.tfm
	/bin/rm *.300pk
