/* is gmp.h in gmp2/ sub direcotory? */
#undef GMP2_PREFIX

#undef HAVE_EXPLICIT_TEMPLATE_INSTANTIATION

#undef HAVE_LIBTIFF
#undef TIFF_HEADER_34

#undef HAVE_READLINE

#undef HAVE_LIBGTS

#undef NO_GETHOSTNAME_PROTO

#undef HTONL_IN_NETINET_IN_H

#undef HAVE_OPENGL

#undef HAVE_INVENTOR
