.TH SURF "1" "March 2001" "surf 1.1.0"
.SH NAME
surf \- visualization of real algebraic geometry
.SH SYNOPSIS
.B surf
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
surf is a script driven visualization tool for real algebraic geometry.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
don't be chatty
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Stephan Endrass, Hans Huelf, Ruediger Oertel, Ralf Schmitt,
Kai Schneider and Johannes Beigel.
.SH "REPORTING BUGS"
Report bugs to the SourceForge bug tracking system at
http://sourceforge.net/tracker/?group_id=3275
.SH COPYRIGHT
Copyright \(co 1996-1997 Friedrich-Alexander-Universitaet Erlangen-Nuernberg,
1997-2001 Johannes Gutenberg-Universitaet Mainz.
.PP
This is free software; you can redistribute it and/or modify it under the
terms of the GNU General Public License; either version 2 of the License,
or any later version.
.SH "SEE ALSO"
The full documentation for
.B surf
is maintained as a Texinfo manual.  If the
.B info
and
.B surf
programs are properly installed at your site, the command
.IP
.B info surf
.PP
should give you access to the complete manual.
